name: Encamera
options:
  bundleIdPrefix: me.freas
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    branch: master
targets:
  Encamera:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Encamera]
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      PRODUCT_BUNDLE_IDENTIFIER: me.freas.encamera
      CODE_SIGN_ENTITLEMENTS: ./Encamera/Encamera.entitlements
    dependencies:
      - package: Sodium
    scheme:
      testTargets:
        - EncameraTests
  EncameraTests:
    platform: iOS
    deploymentTarget: "15.0"
    sources: [EncameraTests]
    type: bundle.unit-test
    dependencies:
      - target: Encamera
