name: Encamera
options:
  bundleIdPrefix: me.freas.encamera
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    branch: master
targets:
  Encamera:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Encamera]
    dependencies:
      - package: Sodium
    scheme:
      testTargets:
        - EncameraTests
  EncameraTests:
    platform: iOS
    deploymentTarget: "15.0"
    sources: [EncameraTests]
    type: bundle.unit-test
    dependencies:
      - target: Encamera
