name: Encamera
options:
  bundleIdPrefix: me.freas
  deploymentTarget: 17.0
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    branch: master
  SwiftUIIntrospect:
    url: https://github.com/siteline/SwiftUI-Introspect
    majorVersion: 1.1.0
  PiwikPROSDK:
    url: https://github.com/PiwikPRO/piwik-pro-sdk-framework-ios
    majorVersion: 1.2.1
  EncameraCore:
    path: ../EncameraCore
  TagCloud:
    url: https://github.com/yarspirin/TagCloud
    majorVersion: 1.0.4

targets:

  WidgetExtension:
    type: app-extension
    configFiles:
      Debug: ./xcconfigs/WidgetExtension-debug.xcconfig
      Release: ./xcconfigs/WidgetExtension-release.xcconfig
    platform: iOS
    sources: [WidgetExtension]
    dependencies:
      - package: Sodium
      - package: EncameraCore
    settings:
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
      CODE_SIGN_IDENTITY: "iPhone Developer"
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: KGJCC745S9
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: WidgetExtension/Info.plist
      INFOPLIST_KEY_CFBundleDisplayName: WidgetExtension
      INFOPLIST_KEY_NSHumanReadableCopyright: ""
      MARKETING_VERSION: 1.0
      PRODUCT_NAME: "$(TARGET_NAME)"
      SKIP_INSTALL: YES
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      executable: WidgetExtension
 
  ShareExtension:
    type: app-extension
    configFiles:
      Debug: ./xcconfigs/ShareExtension-debug.xcconfig
      Release: ./xcconfigs/ShareExtension-release.xcconfig
    platform: iOS
    sources: [ShareExtension]
    dependencies:
      - package: Sodium
      - package: EncameraCore
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
      CODE_SIGN_IDENTITY: "iPhone Developer"
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: KGJCC745S9
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ShareExtension/Info.plist
      INFOPLIST_KEY_CFBundleDisplayName: ShareExtension
      INFOPLIST_KEY_NSHumanReadableCopyright: ""
      MARKETING_VERSION: 1.0
      PRODUCT_NAME: "$(TARGET_NAME)"
      SKIP_INSTALL: YES
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      executable: ShareExtension
  Encamera:
    type: application
    postBuildScripts:
      - script: 'if [ "${CONFIGURATION}" != "Debug" ]; then rm -rf "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/PreviewContent"; fi'
    configFiles:
      Debug: ./xcconfigs/debug.xcconfig
      Release: ./xcconfigs/release.xcconfig
    platform: iOS
    sources: [Encamera]
    storeKitConfiguration: "../../../EncameraCore/Sources/EncameraCore/InAppPurchase/Encamera.storekit"
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ForegroundPrimaryColor
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: NO
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: "1"
      OTHER_LDFLAGS: "-ObjC"
      DEVELOPMENT_ASSET_PATHS:
        "$(SRCROOT)/Encamera/PreviewAssets"
    dependencies:
      - package: Sodium
        link: true
      - target: WidgetExtension
      - package: EncameraCore
      - package: PiwikPROSDK
        link: true
      - package: SwiftUIIntrospect
        link: true
      - framework: StoreKit.framework
        embed: false
      - package: TagCloud
        link: true
    scheme:
      testTargets:
        - EncameraTests

  StoreKitTesting:
    type: application
    configFiles:
      Debug: ./xcconfigs/debug.xcconfig
      Release: ./xcconfigs/release.xcconfig
    platform: iOS
    sources: 
      - path: Encamera
        excludes: [EncameraApp.swift]
      - path: StoreKitTesting
    storeKitConfiguration: "../../../EncameraCore/Sources/EncameraCore/InAppPurchase/Encamera.storekit"
    settings:
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 1.0
      GENERATE_INFOPLIST_FILE: YES
      DEVELOPMENT_TEAM: KGJCC745S9
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ForegroundPrimaryColor
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: NO
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: "1"
      INFOPLIST_KEY_NSPrincipalClass: StoreKitTestingApp
      OTHER_LDFLAGS: "-ObjC"
    dependencies:
      - package: Sodium
        link: true
      - target: ShareExtension
      - package: EncameraCore
      - package: PiwikPROSDK
        link: true
      - package: SwiftUIIntrospect
        link: true
      - framework: StoreKit.framework
        embed: false
      - package: TagCloud
        link: true
    scheme:
      testTargets:



  EncameraTests:
    platform: iOS
    sources: [EncameraTests]
    type: bundle.unit-test
    dependencies:
      - package: Sodium
      - target: Encamera
      - package: EncameraCore
