name: Encamera
options:
  bundleIdPrefix: me.freas
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    branch: master
  EncameraCore:
    path: ../EncameraCore
      #url: https://github.com/akfreas/EncameraCore.git
      #branch: master

targets:


# ShareExtension:
#   type: app-extension
#   platform: iOS
#   sources: [ShareExtension]
#   dependencies:
#     - package: Sodium
#     - package: EncameraCore
#   settings:
#     DEVELOPMENT_TEAM: KGJCC745S9
#     PRODUCT_BUNDLE_IDENTIFIER: me.freas.encamera.ShareExtension
#     CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
#     CODE_SIGN_IDENTITY: "iPhone Developer"
#     CODE_SIGN_STYLE: Automatic
#     CURRENT_PROJECT_VERSION: 1
#     DEVELOPMENT_TEAM: KGJCC745S9
#     GENERATE_INFOPLIST_FILE: YES
#     INFOPLIST_FILE: ShareExtension/Info.plist
#     INFOPLIST_KEY_CFBundleDisplayName: ShareExtension
#     INFOPLIST_KEY_NSHumanReadableCopyright: ""
#     IPHONEOS_DEPLOYMENT_TARGET: 16.2
#     MARKETING_VERSION: 1.0
#     PRODUCT_BUNDLE_IDENTIFIER: me.freas.encamera.ShareExtension
#     PRODUCT_NAME: "$(TARGET_NAME)"
#     SKIP_INSTALL: YES
#     SWIFT_EMIT_LOC_STRINGS: YES
#     SWIFT_VERSION: 5.0
#     TARGETED_DEVICE_FAMILY: "1,2"

  Encamera:
    type: application
    configFiles:
      Debug: ./xcconfigs/debug.xcconfig
      Release: ./xcconfigs/release.xcconfig
    platform: iOS
    deploymentTarget: "15.6"
    sources: [Encamera]
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      PRODUCT_BUNDLE_IDENTIFIER: me.freas.encamera
      CODE_SIGN_ENTITLEMENTS: ./Encamera/Encamera.entitlements
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ForegroundPrimaryColor
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: NO
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: Sodium
        #      - target: ShareExtension
      - package: EncameraCore
      - framework: StoreKit.framework
        embed: false
    scheme:
      testTargets:
        - EncameraTests
  EncameraTests:
    platform: iOS
    deploymentTarget: "15.6"
    sources: [EncameraTests]
    type: bundle.unit-test
    dependencies:
      - package: Sodium
      - target: Encamera
      - package: EncameraCore
