name: Encamera
options:
  bundleIdPrefix: me.freas
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    branch: master
targets:
  Encamera:
    type: application
    configFiles:
      Debug: ./xcconfigs/debug.xcconfig
      Release: ./xcconfigs/release.xcconfig
    platform: iOS
    deploymentTarget: "15.4"
    sources: [Encamera]
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      PRODUCT_BUNDLE_IDENTIFIER: me.freas.encamera
      CODE_SIGN_ENTITLEMENTS: ./Encamera/Encamera.entitlements
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ForegroundPrimaryColor
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: NO
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: Sodium
      - framework: StoreKit.framework
        embed: false
    scheme:
      testTargets:
        - EncameraTests
  EncameraTests:
    platform: iOS
    deploymentTarget: "15.4"
    sources: [EncameraTests]
    type: bundle.unit-test
    dependencies:
      - target: Encamera
