name: Encamera
options:
  bundleIdPrefix: me.freas
packages:
  Sodium:
    url: https://github.com/jedisct1/swift-sodium.git
    branch: master
  EncameraCore:
    path: ../EncameraCore

targets:



  ShareExtension:
    type: app-extension
    configFiles:
      Debug: ./xcconfigs/ShareExtension-debug.xcconfig
      Release: ./xcconfigs/ShareExtension-release.xcconfig
    platform: iOS
    sources: [ShareExtension]
    dependencies:
      - package: Sodium
      - package: EncameraCore
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
      CODE_SIGN_IDENTITY: "iPhone Developer"
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: KGJCC745S9
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ShareExtension/Info.plist
      INFOPLIST_KEY_CFBundleDisplayName: ShareExtension
      INFOPLIST_KEY_NSHumanReadableCopyright: ""
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      MARKETING_VERSION: 1.0
      RODUCT_NAME: "$(TARGET_NAME)"
      SKIP_INSTALL: YES
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      executable: ShareExtension
  Encamera:
    type: application
    configFiles:
      Debug: ./xcconfigs/debug.xcconfig
      Release: ./xcconfigs/release.xcconfig
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Encamera]
    settings:
      DEVELOPMENT_TEAM: KGJCC745S9
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ForegroundPrimaryColor
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      SUPPORTS_MACCATALYST: NO
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: Sodium
      - target: ShareExtension
      - package: EncameraCore
      - framework: StoreKit.framework
        embed: false
    scheme:
      testTargets:
        - EncameraTests
  EncameraTests:
    platform: iOS
    deploymentTarget: "16.0"
    sources: [EncameraTests]
    type: bundle.unit-test
    dependencies:
      - package: Sodium
      - target: Encamera
      - package: EncameraCore
